[package]
name = "pixcap-ffi"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
image = { version = "0.25.10", default-features = false, features = ["png", "jpeg", "webp"] }
pixcap-core = { path = "../pixcap-core" }
pixcap-ipc = { path = "../pixcap-ipc" }
serde_json = "1.0"
